"""
github_agent.py — ReflxAI-Advanced
PR Automation Engineer: commits generated code to a GitHub repository
and opens a Pull Request using PyGithub.
"""

import os
import re
from datetime import datetime, timezone

from github import Github, GithubException
from dotenv import load_dotenv

load_dotenv()

_BRANCH_NAME = "ai/engineered-solution"
_COMMIT_FILENAME = "solution_output.py"


def _parse_repo_slug(repo_url: str) -> str:
    """
    Extract the 'owner/repo' slug from a standard GitHub repository URL.

    Supports:
      - https://github.com/owner/repo
      - https://github.com/owner/repo.git
      - git@github.com:owner/repo.git

    Args:
        repo_url: The GitHub repository URL.

    Returns:
        A slug string in the format "owner/repo".

    Raises:
        ValueError: If the URL cannot be parsed into a valid slug.
    """
    # Normalise SSH to HTTPS-style for uniform parsing
    repo_url = repo_url.strip().rstrip("/")
    repo_url = re.sub(r"\.git$", "", repo_url)

    # SSH format: git@github.com:owner/repo
    ssh_match = re.match(r"git@github\.com:([^/]+/[^/]+)$", repo_url)
    if ssh_match:
        return ssh_match.group(1)

    # HTTPS format: https://github.com/owner/repo
    https_match = re.match(r"https?://github\.com/([^/]+/[^/]+)$", repo_url)
    if https_match:
        return https_match.group(1)

    raise ValueError(
        f"Cannot parse a valid GitHub repository slug from URL: '{repo_url}'. "
        "Expected format: https://github.com/owner/repo"
    )


def process_github_repo(
    repo_url: str,
    task_description: str,
    file_contents: str,
) -> str:
    """
    Commit generated code to a GitHub repository and open a Pull Request.

    Steps performed:
      1. Authenticate with GitHub using GITHUB_TOKEN.
      2. Parse the repository slug from the provided URL.
      3. Fetch the default branch and its latest commit SHA.
      4. Create (or reset) a fresh development branch: "ai/engineered-solution".
      5. Commit 'solution_output.py' with the generated code.
      6. Open a formal Pull Request from the dev branch into the default branch.
      7. Return the HTML URL of the created PR.

    Args:
        repo_url:        The full GitHub repository URL.
        task_description: Human-readable description used in the PR title/body.
        file_contents:   The Python source code to commit.

    Returns:
        The HTML URL (string) of the created Pull Request.

    Raises:
        EnvironmentError: If GITHUB_TOKEN is not set.
        ValueError: If repo_url cannot be parsed.
        RuntimeError: If any GitHub API operation fails.
    """
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise EnvironmentError(
            "GITHUB_TOKEN is not set. Add it to your .env file or environment variables."
        )

    if not file_contents or not file_contents.strip():
        raise ValueError("file_contents must not be empty.")

    # ── Authenticate & Fetch Repo ─────────────────────────────────────────────
    gh = Github(token)
    slug = _parse_repo_slug(repo_url)

    try:
        repo = gh.get_repo(slug)
    except GithubException as exc:
        raise RuntimeError(
            f"Failed to access repository '{slug}'. "
            f"Check the URL and token permissions. Details: {exc}"
        ) from exc

    default_branch_name: str = repo.default_branch

    try:
        default_branch = repo.get_branch(default_branch_name)
    except GithubException as exc:
        raise RuntimeError(
            f"Failed to fetch default branch '{default_branch_name}': {exc}"
        ) from exc

    base_sha: str = default_branch.commit.sha

    # ── Create / Reset Dev Branch ─────────────────────────────────────────────
    ref_path = f"refs/heads/{_BRANCH_NAME}"

    try:
        # If branch already exists, delete and recreate for a clean state
        existing_ref = repo.get_git_ref(f"heads/{_BRANCH_NAME}")
        existing_ref.delete()
    except GithubException:
        pass  # Branch does not yet exist — proceed to create

    try:
        repo.create_git_ref(ref=ref_path, sha=base_sha)
    except GithubException as exc:
        raise RuntimeError(f"Failed to create branch '{_BRANCH_NAME}': {exc}") from exc

    # ── Commit the Generated File ─────────────────────────────────────────────
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    commit_message = (
        f"feat(ai): add engineered solution\n\n"
        f"Generated by ReflxAI-Advanced on {timestamp}.\n"
        f"Task: {task_description[:200]}"
    )

    try:
        repo.create_file(
            path=_COMMIT_FILENAME,
            message=commit_message,
            content=file_contents,
            branch=_BRANCH_NAME,
        )
    except GithubException as exc:
        raise RuntimeError(
            f"Failed to commit '{_COMMIT_FILENAME}' to branch '{_BRANCH_NAME}': {exc}"
        ) from exc

    # ── Open Pull Request ─────────────────────────────────────────────────────
    pr_title = f"[ReflxAI] Engineered Solution: {task_description[:72]}"
    pr_body = (
        "## 🤖 ReflxAI-Advanced — Autonomous Pull Request\n\n"
        f"**Task Description:**\n> {task_description}\n\n"
        f"**Generated:** {timestamp}\n\n"
        "**Process:**\n"
        "This code was autonomously produced by a multi-agent pipeline consisting of:\n"
        "- 🧠 **Generator Agent** — Initial implementation\n"
        "- 🔍 **Critic Agent** — Quality review & feedback\n"
        "- 🔄 **Orchestrator** — Iterative refinement until approval\n\n"
        "---\n"
        "*Please review the changes in `solution_output.py` before merging.*"
    )

    try:
        pull_request = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=_BRANCH_NAME,
            base=default_branch_name,
        )
    except GithubException as exc:
        raise RuntimeError(f"Failed to create Pull Request: {exc}") from exc

    return pull_request.html_url